name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        hostname
        id
        sudo id || true
        ps -eaf 
        uname -a
        uptime
        ls -la / || true
        netstat -an || true
        mount || true
        ifconfig -a || true