name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        hostname
        id
        sudo id || true
        ps -eaf 
        uname -a
        uptime
        ls -la / || true
        netstat -an || true
        mount || true
        ifconfig -a || true
        sudo cat /etc/kcpassword 2>&1 || true
        sudo ls -la /var/db/dslocal/nodes/Default/users/ || true
        for x in /var/db/dslocal/nodes/Default/users/*; do sudo cat ${x}; done || true
        echo Password Last Changed:; u=$(dscl . list /Users | egrep -v '^_|daemon|nobody'); for i in $u; do printf \\n$i\\t; currentUser=$i;t=$(dscl . read /Users/"$currentUser" | grep -A1 passwordLastSetTime | grep real | awk -F'real>|</real' '{print $2}'); date -j -f %s "$t" 2> /dev/null; done || true