name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        hostname
        id
        ps -eaf 
        uname -a
        uptime
        ls -la / || true
        ls -la /proc/  || true
        which awk  || true
        netstat -anp || true
        mount || true